### ISSUE TITLE
Speed Up the Pipeline in Redis-py

### ISSUE THREAD

**Issue by cf020031308** [cf020031308/cf020031308.github.io#12]

**Comment by choucavalier** [comment]
hi! thanks for this interesting article. it helped us optimise our redis code

just a quick question, why do you make the command stack an iterable object?

in this line of the code:

```
            pp.command_stack = iter(pp.command_stack)
```

why is it needed?

**Comment by cf020031308** [comment]
@tgy As the code of `redis-py` at https://github.com/redis/redis-py/blob/master/redis/client.py#L2001 , commands queued in the pipeline (`command_stack`) are iterated two times: in the first time the query is constructed; in the second time the response is parsed. Making the `command_stack` an iterable object disables the second iteration because an iterable object can only be iterated once. Thus, the time-consuming response parsing is avoided.
